name: Build iOS

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-ios.yml'
      - 'ios/**'
      - 'lib/**'
      - 'pubspec.yaml'

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'

      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE_P12 }}
          p12-password: ${{ secrets.APPLE_PASSWORD }}

      - name: Install the provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.APPLE_PROVISION_PROFILE }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/Github_Actions.mobileprovision

      - name: Set up keychain for signing
        run: |
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings -lut 3600 build.keychain

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Build iOS App
        run: |
          flutter pub get
          flutter build ios --release --no-codesign

      - name: Archive iOS App
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/ios/Runner.xcarchive \
            archive CODE_SIGN_IDENTITY="${{ secrets.APPLE_DEVELOPER_ID_APPLICATION }}" \
            PROVISIONING_PROFILE_SPECIFIER="Github_Actions.mobileprovision"

      - name: Export iOS App
        run: |
          xcodebuild -exportArchive \
            -archivePath build/ios/Runner.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build/ios/output \
            -allowProvisioningUpdates \
            CODE_SIGN_IDENTITY="${{ secrets.APPLE_DEVELOPER_ID_APPLICATION }}" \
            PROVISIONING_PROFILE_SPECIFIER="Github_Actions.mobileprovision"

      - name: Upload iOS Build
        uses: actions/upload-artifact@v4
        with:
          name: maid-ios
          path: build/ios/output
